---
services:
  - docker
language: python
python: "2.7"
cache: pip

sudo: required
dist: xenial

env:
  global:
  matrix:
    - TEST=basic db_name=telegraf rp_name=rp_4d
    - TEST=setup db_name=telegraf_30d rp_name=rp_30d
    - TEST=migrate db_name=test_4d rp_name=rp_4d db_name_source=test
    - TEST=compact db_name=telegraf rp_name=rp_4d
    # - TEST=recreate_cqs db_name=test_4d rp_name=rp_4d

before_install:
  # Make sure everything's up to date.
  #- sudo apt-get update -qq

install:
  # start influxdb (will take some time to be reachable!)
  - docker run -d --name influxdb -p 8086:8086 -v $PWD/integration/influxdb:/var/lib/influxdb influxdb:alpine

  # start telegraf to continuously write data to influxdb
  - >
    if [ "$TEST" = "setup" -o "$TEST" = "compact" ]; then
    docker run -d --net host --name telegraf telegraf:alpine; sleep 10;
    fi

  # Install ansible and jq.
  - "pip install ansible jq"

  # Add ansible.cfg to pick up roles path.
  - printf "[defaults]\nroles_path = ../" > ansible.cfg

  # Seed influxdb (after pip, so influxdb will be reachable)
  - >
    if [ "$TEST" = "migrate" -o "$TEST" = "recreate_cqs" ]; then
    ./tests/seed.sh 1m 10s "$(date -d -1hour +"%Y-%m-%d %H:%M:00")" seq+step10;
    fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - yes | ansible-playbook -i tests/inventory tests/test.yml --connection=local

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    yes | ansible-playbook -i tests/inventory tests/test.yml --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1);

  # TEST = basic
  - >
    if [ "$TEST" = "basic" ]; then
    result=$(curl http://localhost:8086/query?db=$db_name --data-urlencode 
    "q=SHOW RETENTION POLICIES" | jq .results[0].series[0].values[1][0] |tr -d '"');
    [ "$result" = "$rp_name" ]
    && (echo "Retention policy test: pass"; exit 0)
    || (echo -e "Retention policy test: fail ('$result' != '$rp_name')"; exit 1);
    fi

  # TEST = setup (wait for CQ to run)
  - >
    if [ "$TEST" = "setup" ]; then
    sleep 10;
    curl http://localhost:8086/query?db=$db_name --data-urlencode
    "q=SELECT ROUND(MEAN(usage_user)) AS usage_user FROM $db_name.$rp_name.cpu WHERE time >= now() -1m" | jq .;
    result=$(curl http://localhost:8086/query?db=$db_name --data-urlencode 
    "q=SELECT ROUND(MEAN(usage_user)) AS usage_user FROM $db_name.$rp_name.cpu WHERE time >= now() -1m" 
    | jq .results[0].series[0].values[0][1]);
    [ "$result" -gt 0 ]
    && (echo "Setup test: pass"; exit 0)
    || (echo -e "Setup test: fail ($result)"; exit 1);
    fi

  # TEST = migrate
  - >
    if [ "$TEST" = "migrate" ]; then
    curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT * FROM $db_name.$rp_name.test";
    result=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode 
    "q=SELECT * FROM $db_name.$rp_name.test" | jq .results[0].series[0].values[0][1]);
    [ "$result" = "35" ]
    && (echo "Aggregation test: pass"; exit 0)
    || (echo "Aggregation test failed: ('$result' != 35)"; exit 1);
    curl -s http://localhost:8086/query?db=$db_name --data-urlencode
    "q=SHOW CONTINUOUS QUERIES" | jq . | grep 'cq_cpu_';
    sed -i -e 's#^\( *interval: "\)1m\(".*\)$#\130s\2#' -e 's#^\(.*every: "\)1m\(".*\)$#\130s\2#' ./tests/vars/migrate.yml;
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --extra-vars=recreate_cqs=yes 2>&1
    | grep -A1 -e 'Drop continuous';
    result=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode
    "q=SHOW CONTINUOUS QUERIES" | jq .);
    result1="$(echo "$result" | grep "_30s")";
    result2="$(echo "$result" | grep "_1m")";
    [ -n "$result1" ] 
    && (echo "CQ update test: pass (new CQ exists)"; exit 0)
    || (echo "CQ update test: fail (new CQ does not exist)"; exit 1);
    [ -z "$result2" ] 
    && (echo "CQ update test: pass (old CQ is gone)"; exit 0)
    || (echo "CQ update test: fail (old CQ still exists = $result2)"; exit 1); 
    ;
    fi

  # TEST = compact
  - >
    if [ "$TEST" = "compact" ]; then
    curl -s http://localhost:8086/query?db=$db_name --data-urlencode 
    "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.autogen.cpu";
    curl -s http://localhost:8086/query?db=$db_name --data-urlencode 
    "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.$rp_name.cpu";
    result1=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode 
    "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.$rp_name.cpu" | jq .results[0].series[0].values[0][1]);
    result2=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode 
    "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name..cpu" | jq .results[0].series[0].values[0][1]);
    [ "$result1" = "$result2" ]
    && (echo "Compact test: pass (new RP is default)"; exit 0)
    || (echo -e "Compact test: fail (new RP is not default):\n$result1 != $result2"; exit 1);
    result3=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode 
    "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.autogen.cpu" | jq .results[0].error);
    [ -n "$result3" ]
    && (echo "Compact test: pass (source is gone)"; exit 0)
    || (echo "Compact test: fail (source still exists)"; exit 1);
    fi

  - >
    if [ "$TEST" = "recreate_cqs" ]; then
    curl -s http://localhost:8086/query?db=$db_name --data-urlencode
    "q=SHOW CONTINUOUS QUERIES" | jq .;
    sed -i .bak -e 's#^\( *continuous_query: { interval: "\)10s\(".*\)$#\115s\2#' ./tests/vars/recreate_cqs.yml;
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --extra-vars=recreate_cqs=yes
    | grep -q 'changed=0.*failed=0';
    curl -s http://localhost:8086/query?db=$db_name --data-urlencode
    "q=SHOW CONTINUOUS QUERIES" | jq .;
    fi

after_script:
  - curl http://localhost:8086/query?db=$db_name --data-urlencode "q=SHOW DATABASES";
  - curl http://localhost:8086/query?db=$db_name --data-urlencode "q=SHOW RETENTION POLICIES";
  - curl http://localhost:8086/query?db=$db_name --data-urlencode "q=SHOW MEASUREMENTS";
  - >
    if [ "$TEST" = "setup" ]; then
    curl http://localhost:8086/query?db=$db_name --data-urlencode
    "q=SELECT usage_user FROM $db_name.$rp_name.cpu" | jq .;
    fi
  - >
    if [ "$TEST" = "migrate" ]; then
    curl http://localhost:8086/query?db=$db_name_source --data-urlencode 
    "q=SELECT * FROM $db_name_source.autogen.test" | jq .results[0].series[0];
    curl http://localhost:8086/query?db=$db_name_source --data-urlencode 
    "q=SELECT MEAN(value) FROM $db_name_source.autogen.test" | jq .results[0].series[0];
    curl http://localhost:8086/query?db=$db_name --data-urlencode 
    "q=SELECT MEAN(value) FROM $db_name.$rp_name.test" | jq .results[0].series[0];
    fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

